### ISSUE TITLE
请问TFVT_HRI的模型可以公布吗

### ISSUE THREAD

**Issue by leecuijiao** [PaddlePaddle/PaddleRobotics#4]
代码中 MobileNetV2_Pretrained = 'pretrain_models/MobileNetV2_pretrained' 的模型可以提供吗

**Comment by xueeinstein** [comment]
可以的 https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV2_pretrained.tar

**Comment by leecuijiao** [comment]
主动交互的模型可以公布吗？就是基于专家标注的数据训练的模型
